mode: control
crossings:
  GDENABY:
    lower:
      - S862
      - S706
      - S883
    raise: auto
  GDODWORTH:
    lower:
      - RBY1045AM
      - RBY1046AM
    raise: auto
  GBARNSLEY:
    lower:
      - SBY1027
      - RBY1032AM
      - RBY1038AM
      - RBY1070AM
      - RBY1030AM
    raise: auto
  GHOLMES:
    lower:
      - S749
      - R1066_1
      - R218_1M
      - R213_1M
      - R213_2M
      - R213_3M
      - R1064
    raise: auto
  GBEIGHTON:
    lower:
      - RBX33AM
      - RBX7
    raise: auto
